---
- name: Install Softwares
  hosts: worker
  vars:
    packages:
      - name: nginx
        required: True
      - name: mysql
        required: True
      - name: apache
        required: True
  tasks:
    - name: Installing {{ item.name }} on Debian Systems.
      apt:
        name: "{{ item.name }}"
        state: absent
      when: item.required == True
      loop: "{{ packages }}"
