---
- name: Install Nginx
  hosts: all
  tasks:
    - name: Install Nginx on Debian Systems
      apt:
        name: nginx
        state: present
      when: ansible_os_family == "Debian" and ansible_distribution_version == "16.04"

    - name: Install Nginx on Redhat Systems
      yum:
        name: nginx
        state: present
      when: ansible_os_family == "Redhat" or ansible_os_family == "CentOS" or ansible_os_family == "Suse"