---
# tasks file for flask_web
- name: Install Python Flask Dependencies
  pip:
    name: "{{ item }}"
  with_items:
    - flask
    - flask-mysql

- name: Copy web server source code
  copy:
    src: /root/MasteringAnsible/Includes/app.py
    dest: /opt/app.py

- name: Starting the Web Server
  shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &
