---
- name: test ftp upload
  hosts: localhost
  tasks: 
    - name: install lftp
      yum:
        name: lftp
    - name: upload file
      shell: >
        lftp client1.sikkim.com <<EOF
        cd pub
        put /etc/hosts
        EOF
