---
- name: Cleaning up the web server
  hosts: client
  tasks:
    - name: Stopping the Web Server Services
      service:
        name: httpd
        state: stopped
      notify:
        - remove httpd
    - name: Removing the index file
      file:
        path: /var/www/html/index.html
        state: absent
  handlers:
    - name: remove httpd
      yum:
        name: httpd
        state: absent
