---
- name: Demonstrating how loop works
  hosts: all
  gather_facts: false
  vars:
    my_services:
      - crond
      - sshd
  tasks:
    - name: Start Some Services
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ my_services }}"