---
- name: Creating ACTIVE DIRECTORY Computer Object
  hosts: dc1
  tasks:
    - name: Creating the Computer Object
      win_domain_computer:
        name: "{{ item }}"
        sam_account_name: "{{ item}}$"
        dns_hostname: "{{ item }}.sikkim.com"
        ou: "OU=Servers,DC=Sikkim,DC=Com"
        description: Critical Servers
        enabled: yes
        state: present
      with_items:
        - mangan
        - namchi
        - gangtok
        - ranipool
        - pakkim
        - jorethang
      register: Computer_Account_Creation
      #delegate_to: my_windows_bridge.my_org.local

    - name: What is the Output???
      debug:
        msg: Computer_Account_Creation.stdout

    # - name: 
    #   win_domain_computer:
    #     name: "{{ ComputerName }}"
    #     state: absent
    #   register: Computer_Account_Deletion

    # - name: What is the Output???
    #   debug:
    #     msg: Computer_Account_Deletion.stdout


  #   - name: Create Active Directory OU
  #     win_dsc:
  #       resource_name: ADOrganizationalUnit_CreateADOU_Config
  #       name: Servers
  #       path: "DC=Sikkim,DC=Com"
  #       ensure: present
  #       ProtectedFromAccidentalDeletion: True
  #       Description: "This OU is only for servers"
  #       PsDscRunAsCredential_username: '{{ ansible_user }}'
  #       PsDscRunAsCredential_password: '{{ ansible_ssh_pass }}'
  # roles:
  #   - Create_ActiveDirectory_OU

