---
- name: Creating ACTIVE DIRECTORY Computer Object
  hosts: dc1
  tasks:
    - name: Deleting the Computer object
      win_domain_computer:
        name: "{{ item }}"
        state: absent
      with_items:
        - mangan
        - namchi
        - gangtok
        - ranipool
        - pakkim
        - jorethang
      register: Computer_Account_Deletion

    - name: What is the Output???
      debug:
        msg: Computer_Account_Deletion.stdout
