---
- name: Set up Web Server
  hosts: client
  force_handlers: True
  tasks:
    - name: Install httpd
      yum:
        name: httpd
        state: latest
    - name: Copy index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web
    - name: Copy nothing.html
      copy:
        src: /tmp/nothing.html
        dest: /var/www/html/index.html
  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted
