---
- name: New Index.html
  hosts: client
  tasks:
    - name: Installing httpd
      yum:
        name: httpd
        state: present
    - name: Creating the directory
      file:
        path: /var/www/html
        state: directory
        mode: "0755"
    - name: copy Index.html
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart-web
  handlers:
    - name: restart-web
      service:
        name: httpd
        state: restarted
