---
- name: Installing Softwares
  hosts: client
  tasks:
    - name: Installing httpd and vsftpd
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - httpd
        - vsftpd
    - name: Ensuring that the services are running
      service:
        name: "{{ item }}"
        state: started
      with_items:
        - httpd
        - vsftpd
