---
- name: Install only when condition meets
  gather_facts: yes
  hosts: all
  tasks:
  - name: Install VSFTPD only if Sufficient Space on /var/ftp
    package:
      name: vsftpd
      state: latest
    with_items: "{{ ansible_mounts }}"
    when: item.mount == "var/ftp" and item.size_available > 10000000000000