---
- name: Setup Web Server
  hosts: clients
  tasks:
    - name: install httpd
      yum:
        name: httpd
        state: latest
    - name: Copy index file
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web
    - name: Copy Nothing - Simulating a Failure
      copy:
        src: /tmp/nothing
        dest: /var/www/html/nothing.html
  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted
