---
- name: Disabling the Root Login on all the systems
  hosts: all
  tasks:
    - name: Changing the sshd_config File
      lineinfile:
        dest: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin no"
    - name: Validating the Change
      ansible.builtin.shell: cat /etc/ssh/sshd_config | grep -i PermitRootLogin
      register: RootLoginStatus
    - name: Viewing the Change
      debug:
        msg: "{{ RootLoginStatus.stdout }}"
