---
- name: Set Up A Web Server
  hosts: linuxclients
  force_handlers: True
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: latest
    - name: Copy the Index.html file
      copy:
        src: /tmp/index.html
        dest: /var/www/html/index.html
      notify:
        - restart_web
    - name: Copy Nothing. Forcing a failure
      copy:
        src: /tmp/nothing.html
        dest: /var/www/html/nothing.html
  handlers:
    - name: restart_web
      service:
        name: httpd
        state: restarted
