---
- name: This playbook installs VIM
  hosts: ansibletower
  gather_facts: false
  tasks:
    - name: Installing VIM
      yum: 
        name: vim
        state: installed

- name: Uninstalling VSFTPD
  hosts: centos
  gather_facts: false
  tasks:
    - name: Uninstalling few stuffs
      yum: 
        name: vsftpd
        state: absent

