---
- name: Create Active Directory OU
  win_dsc:
    resource_name: ADOrganizationalUnit
    name: Servers
    path: "DC=Sikkim,DC=Com"
    ensure: present
    ProtectedFromAccidentalDeletion: True
    Description: "This OU is only for servers"
