- hosts: all
  vars:
    my_user: linda

  superusers:
    - root
    - linda

  tasks:
    - name: Run only if Linda is superusers
      user:
        name: "{{ my_user }}"
        groups: wheel
        append: yes
      when: my_user in superusers
