---
- name: Using the TAGS
  hosts: client
  tasks:
    - name: Installing the Net Analysis Tools
      package:
        name: "{{ item }}"
        state: installed
      with_items:
        - nmap
        - wireshark
      tags:
        - net_analysis
    - name: Installing the LAMP Stack
      package:
        name: "{{ item }}"
        state: installed
      with_items:
        - mariadb-server
        - httpd
      tags:
        - lamp
