---
- name: Deploying an application that uses FLASK
  hosts: ubuntuclients
  tasks:
    - include: tasks/connectivity_check.yml

    - include: tasks/install_dependencies.yml

    - include: tasks/deploy_db.yml

    - include: tasks/deploy_web.yml
