---
- name: Using Multiple Conditions
  hosts: all
  tasks: 
    - name: Installing the package
      package:
        name: httpd
        state: installed
      when: 
        - ansible_distribution == "RedHat"
        - ansible_memfree_mb > 512
