---
- name: When Demo
  hosts: all
  vars:
    supported_distros:
      - RedHat
      - CentOS
      - Fedora
  tasks:
    - name: Install RH Family Specific Packages
      yum: 
        name: httpd
        state: absent
      when: ansible_distribution in supported_distros

