---
- name: Registered variable usage as a loop list
  hosts: client
  tasks:
    - name: Creating a backup of the spooler directory
      file:
        path: /var/bkspool
        state: directory

    - name: Retrieve the list of home directories
      command: ls /home
      register: home_dirs

    - name: Add home dirs to the backup spooler
      file:
        path: /var/bkspool/{{ item }}
        src: /home/{{ item }}
        state: link
      loop: "{{ home_dirs.stdout_lines }}"
